ALTER TABLE quiz ALTER COLUMN mode TYPE VARCHAR(20);
ALTER TABLE quiz DROP CONSTRAINT quiz_mode_check;
ALTER TABLE quiz ADD CONSTRAINT quiz_mode_check CHECK (mode IN ('LEARN', 'EXAM', 'BUZZER', 'PRESENTATION'));
